SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER TABLE `wildschaap`.`ws_workshop` 
ADD COLUMN `deleted` TINYINT(1) NOT NULL DEFAULT 0 AFTER `omschrijving`;

ALTER TABLE `wildschaap`.`ws_sessie` 
ADD COLUMN `deleted` TINYINT(1) NOT NULL DEFAULT 0 AFTER `capaciteit`;

ALTER TABLE `wildschaap`.`ws_cursist` 
ADD COLUMN `deleted` TINYINT(1) NOT NULL DEFAULT 0 AFTER `opmerkingen`;

ALTER TABLE `wildschaap`.`ws_inschrijving` 
ADD COLUMN `deleted` TINYINT(1) NOT NULL DEFAULT 0 AFTER `betaald`;

DROP TABLE IF EXISTS `wildschaap`.`ws_betaling` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
